# Generated by Django 5.2 on 2025-06-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="participants",
            field=models.ManyToManyField(blank=True, related_name="participants", to="employee.employee"),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_datetime__gt", models.F("start_datetime"))), name="end_after_start"
            ),
        ),
    ]
