# Generated by Django 5.2 on 2025-06-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manages_department",
                to="employee.employee",
            ),
        ),
    ]
