# Generated by Django 5.2 on 2025-06-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "position",
                    models.CharField(
                        choices=[("employee", "Employee"), ("manager", "Manager")], default="employee", max_length=20
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="department.department"
                    ),
                ),
            ],
        ),
    ]
